const FETCH_FEATURED_PENDING = 'FETCH_FEATURED_PENDING';
const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';
const FETCH_FEATURED_ERROR = 'FETCH_FEATURED_ERROR';

export {
    FETCH_FEATURED_PENDING,
    FETCH_FEATURED_SUCCESS,
    FETCH_FEATURED_ERROR
};