const ADD_TO_BASKET = 'ADD_TO_BASKET';
const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
const LOAD_BASKET_DATA = 'LOAD_BASKET_DATA';

export {
    ADD_TO_BASKET,
    REMOVE_FROM_BASKET,
    LOAD_BASKET_DATA
}
