const FETCH_BY_CATEGORY = 'FETCH_BY_CATEGORY';
const FETCH_BY_CATEGORY_SUCCESS = 'FETCH_BY_CATEGORY_SUCCESS';
const FETCH_BY_CATEGORY_ERROR = 'FETCH_BY_CATEGORY_ERROR';

export {
    FETCH_BY_CATEGORY,
    FETCH_BY_CATEGORY_SUCCESS,
    FETCH_BY_CATEGORY_ERROR
}