const FETCH_FEATURED_PENDING = 'FETCH_FEATURED_PENDING';
const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';
const FETCH_FEATURED_ERROR = 'FETCH_FEATURED_ERROR';

const FETCH_BY_CATEGORY = 'FETCH_BY_CATEGORY';
const FETCH_BY_CATEGORY_SUCCESS = 'FETCH_BY_CATEGORY_SUCCESS';
const FETCH_BY_CATEGORY_ERROR = 'FETCH_BY_CATEGORY_ERROR';

export {
    FETCH_FEATURED_PENDING,
    FETCH_FEATURED_SUCCESS,
    FETCH_FEATURED_ERROR,
    FETCH_BY_CATEGORY,
    FETCH_BY_CATEGORY_SUCCESS,
    FETCH_BY_CATEGORY_ERROR
}
