const FETCH_FEATURED = 'FETCH_FEATURED';
const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';
const FETCH_FEATURED_ERROR = 'FETCH_FEATURED_ERROR';

export {
    FETCH_FEATURED,
    FETCH_FEATURED_SUCCESS,
    FETCH_FEATURED_ERROR
}